FROM ubuntu:18.04

RUN apt update
RUN apt install -y python3.6 python3-pip

RUN apt install -y git

RUN git clone https://github.com/tf-encrypted/tf-encrypted /tf-encrypted

WORKDIR /tf-encrypted
RUN pip3 install protobuf==3.5.2
RUN pip3 install -e .

COPY requirements-src.txt /req

WORKDIR /
RUN pip3 install -r /req

