version: 1
disable_existing_loggers: False,
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    style: '%'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  mpcbenchrunner:
    level: DEBUG
root:
  level: DEBUG
  handlers: [console]