version: "3.2"
services:
  mongo:
    image: mongo:5.0.9
    ports:
      - "0.0.0.0:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: nZ85
  mongo-express:
    image: mongo-express:0.54.0
    restart: "unless-stopped"
    depends_on:
      - mongo
    ports:
      - "127.0.0.1:5051:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://root:nZ85@mongo:27017?ssl=false"
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: nZ85